services:
  - type: web
    name: chopping-api
    env: ruby
    buildCommand: "./render-build.sh"
    startCommand: "bundle exec rails server -b 0.0.0.0"
    envVars:
      - key: RAILS_ENV
        value: production
